"""empty message

Revision ID: 095508950ae2
Revises: 
Create Date: 2023-02-07 21:19:14.721155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095508950ae2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('composer_style',
    sa.Column('composer_id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composer_id'], ['composers.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ),
    sa.PrimaryKeyConstraint('composer_id', 'style_id')
    )
    op.create_table('contemporaries',
    sa.Column('composer_id', sa.Integer(), nullable=False),
    sa.Column('contemporary_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composer_id'], ['composers.id'], ),
    sa.ForeignKeyConstraint(['contemporary_id'], ['composers.id'], ),
    sa.PrimaryKeyConstraint('composer_id', 'contemporary_id'),
    sa.UniqueConstraint('composer_id', 'contemporary_id', name='unique_contemporaries')
    )
    with op.batch_alter_table('contemporaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contemporaries_composer_id'), ['composer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contemporaries_contemporary_id'), ['contemporary_id'], unique=False)

    with op.batch_alter_table('contemoparaies', schema=None) as batch_op:
        batch_op.drop_index('ix_contemoparaies_composer_id')
        batch_op.drop_index('ix_contemoparaies_contemporary_id')

    op.drop_table('contemoparaies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contemoparaies',
    sa.Column('composer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contemporary_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['composer_id'], ['composers.id'], name='contemoparaies_composer_id_fkey'),
    sa.ForeignKeyConstraint(['contemporary_id'], ['composers.id'], name='contemoparaies_contemporary_id_fkey'),
    sa.UniqueConstraint('composer_id', 'contemporary_id', name='unique_contemoparaies')
    )
    with op.batch_alter_table('contemoparaies', schema=None) as batch_op:
        batch_op.create_index('ix_contemoparaies_contemporary_id', ['contemporary_id'], unique=False)
        batch_op.create_index('ix_contemoparaies_composer_id', ['composer_id'], unique=False)

    with op.batch_alter_table('contemporaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contemporaries_contemporary_id'))
        batch_op.drop_index(batch_op.f('ix_contemporaries_composer_id'))

    op.drop_table('contemporaries')
    op.drop_table('composer_style')
    op.drop_table('styles')
    # ### end Alembic commands ###
