"""empty message

Revision ID: 9ccdc7af024d
Revises: cc08c7e10b31
Create Date: 2023-02-11 14:38:18.295446

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9ccdc7af024d'
down_revision = 'cc08c7e10b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=250), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('performer_title',
                    sa.Column('performers_id', sa.Integer(), nullable=False),
                    sa.Column('title_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['performers_id'], ['performers.id'], ),
                    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
                    sa.PrimaryKeyConstraint('performers_id', 'title_id')
                    )
    op.create_table('composer_title',
                    sa.Column('composer_id', sa.Integer(), nullable=False),
                    sa.Column('title_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['composer_id'], ['composers.id'], ),
                    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
                    sa.PrimaryKeyConstraint('composer_id', 'title_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contemporaries', schema=None) as batch_op:
        batch_op.drop_constraint('unique_contemporaries', type_='unique')

    op.drop_table('composer_title')
    op.drop_table('performer_title')
    op.drop_table('titles')
    # ### end Alembic commands ###
